// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzLDAIKKKZqFYY7JcV03oibguxECq8H0g',
    appId: '1:1086014943183:web:9913fcabbfdd8a5568acba',
    messagingSenderId: '1086014943183',
    projectId: 'medilink-1aaf4',
    authDomain: 'medilink-1aaf4.firebaseapp.com',
    storageBucket: 'medilink-1aaf4.firebasestorage.app',
    measurementId: 'G-V1Z9WGZCWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCatL-8gGGrtvvcslGKRkBTp8B0KG10Xbc',
    appId: '1:1086014943183:android:e93e7886f7b770ae68acba',
    messagingSenderId: '1086014943183',
    projectId: 'medilink-1aaf4',
    storageBucket: 'medilink-1aaf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBllbYeTjp5e0u_jJiEH2HtgVs3-zzHv1M',
    appId: '1:1086014943183:ios:e9035e281676665068acba',
    messagingSenderId: '1086014943183',
    projectId: 'medilink-1aaf4',
    storageBucket: 'medilink-1aaf4.firebasestorage.app',
    iosBundleId: 'com.example.medilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBllbYeTjp5e0u_jJiEH2HtgVs3-zzHv1M',
    appId: '1:1086014943183:ios:e9035e281676665068acba',
    messagingSenderId: '1086014943183',
    projectId: 'medilink-1aaf4',
    storageBucket: 'medilink-1aaf4.firebasestorage.app',
    iosBundleId: 'com.example.medilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzLDAIKKKZqFYY7JcV03oibguxECq8H0g',
    appId: '1:1086014943183:web:ab0147d7d73eb80068acba',
    messagingSenderId: '1086014943183',
    projectId: 'medilink-1aaf4',
    authDomain: 'medilink-1aaf4.firebaseapp.com',
    storageBucket: 'medilink-1aaf4.firebasestorage.app',
    measurementId: 'G-PLH82E5H14',
  );
}
